<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TestDetailsViewForm.aspx.cs" Inherits="AnyTest2_1.TestDetailsViewForm" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Test DetailsView</title>
   	<meta name="vs_snapToGrid" content="False" />
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
</head>
<body>
    <form id="TestDetailsViewForm" runat="server">
        <asp:DetailsView ID="DetailsView1" AutoGenerateRows="true" AutoGenerateInsertButton="true" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AllowPaging="true" runat="server" />
    </form>
</body>
</html>
