-- http://www.dba-oracle.com/t_in_vs_exists_sql.htm
-- http://explainextended.com/2009/06/16/in-vs-join-vs-exists/
-- http://sqlperformance.com/2012/12/t-sql-queries/left-anti-semi-join
-- http://sqlserverplanet.com/tsql/comparing-exists-vs-left-join-where-not-null
-- http://blog.sqlauthority.com/2010/06/05/sql-server-convert-in-to-exists-performance-talk/
-- http://sqlserverplanet.com/tsql/using-where-exists