//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServiceISoap", Namespace="http://tempuri.org/")]
public partial class ServiceI : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HeloWordOperationCompleted;
    
    private System.Threading.SendOrPostCallback DoSmthWithTestClassSimpleOperationCompleted;
    
    private System.Threading.SendOrPostCallback DoSmthWithTestClassOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveXmlOperationCompleted;
    
    private System.Threading.SendOrPostCallback MethodWithoutParametersOperationCompleted;
    
    /// <remarks/>
    public ServiceI() {
        string urlSetting = System.Configuration.ConfigurationManager.AppSettings["URL"];
        if ((urlSetting != null)) {
            this.Url = urlSetting;
        }
        else {
            this.Url = "http://localhost/ServiceI/ServiceI.asmx";
        }
    }
    
    /// <remarks/>
    public event HeloWordCompletedEventHandler HeloWordCompleted;
    
    /// <remarks/>
    public event DoSmthWithTestClassSimpleCompletedEventHandler DoSmthWithTestClassSimpleCompleted;
    
    /// <remarks/>
    public event DoSmthWithTestClassCompletedEventHandler DoSmthWithTestClassCompleted;
    
    /// <remarks/>
    public event SaveXmlCompletedEventHandler SaveXmlCompleted;
    
    /// <remarks/>
    public event MethodWithoutParametersCompletedEventHandler MethodWithoutParametersCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HeloWord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HeloWord() {
        object[] results = this.Invoke("HeloWord", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHeloWord(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HeloWord", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHeloWord(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HeloWordAsync() {
        this.HeloWordAsync(null);
    }
    
    /// <remarks/>
    public void HeloWordAsync(object userState) {
        if ((this.HeloWordOperationCompleted == null)) {
            this.HeloWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHeloWordOperationCompleted);
        }
        this.InvokeAsync("HeloWord", new object[0], this.HeloWordOperationCompleted, userState);
    }
    
    private void OnHeloWordOperationCompleted(object arg) {
        if ((this.HeloWordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HeloWordCompleted(this, new HeloWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoSmthWithTestClassSimple", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public TestClassSimple DoSmthWithTestClassSimple(TestClassSimple TestClassSimple) {
        object[] results = this.Invoke("DoSmthWithTestClassSimple", new object[] {
                    TestClassSimple});
        return ((TestClassSimple)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDoSmthWithTestClassSimple(TestClassSimple TestClassSimple, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DoSmthWithTestClassSimple", new object[] {
                    TestClassSimple}, callback, asyncState);
    }
    
    /// <remarks/>
    public TestClassSimple EndDoSmthWithTestClassSimple(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TestClassSimple)(results[0]));
    }
    
    /// <remarks/>
    public void DoSmthWithTestClassSimpleAsync(TestClassSimple TestClassSimple) {
        this.DoSmthWithTestClassSimpleAsync(TestClassSimple, null);
    }
    
    /// <remarks/>
    public void DoSmthWithTestClassSimpleAsync(TestClassSimple TestClassSimple, object userState) {
        if ((this.DoSmthWithTestClassSimpleOperationCompleted == null)) {
            this.DoSmthWithTestClassSimpleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoSmthWithTestClassSimpleOperationCompleted);
        }
        this.InvokeAsync("DoSmthWithTestClassSimple", new object[] {
                    TestClassSimple}, this.DoSmthWithTestClassSimpleOperationCompleted, userState);
    }
    
    private void OnDoSmthWithTestClassSimpleOperationCompleted(object arg) {
        if ((this.DoSmthWithTestClassSimpleCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DoSmthWithTestClassSimpleCompleted(this, new DoSmthWithTestClassSimpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoSmthWithTestClass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public TestClass DoSmthWithTestClass(TestClass TestClass) {
        object[] results = this.Invoke("DoSmthWithTestClass", new object[] {
                    TestClass});
        return ((TestClass)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDoSmthWithTestClass(TestClass TestClass, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DoSmthWithTestClass", new object[] {
                    TestClass}, callback, asyncState);
    }
    
    /// <remarks/>
    public TestClass EndDoSmthWithTestClass(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TestClass)(results[0]));
    }
    
    /// <remarks/>
    public void DoSmthWithTestClassAsync(TestClass TestClass) {
        this.DoSmthWithTestClassAsync(TestClass, null);
    }
    
    /// <remarks/>
    public void DoSmthWithTestClassAsync(TestClass TestClass, object userState) {
        if ((this.DoSmthWithTestClassOperationCompleted == null)) {
            this.DoSmthWithTestClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoSmthWithTestClassOperationCompleted);
        }
        this.InvokeAsync("DoSmthWithTestClass", new object[] {
                    TestClass}, this.DoSmthWithTestClassOperationCompleted, userState);
    }
    
    private void OnDoSmthWithTestClassOperationCompleted(object arg) {
        if ((this.DoSmthWithTestClassCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DoSmthWithTestClassCompleted(this, new DoSmthWithTestClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SaveXml(string name, System.Xml.XmlNode XmlBody) {
        object[] results = this.Invoke("SaveXml", new object[] {
                    name,
                    XmlBody});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveXml(string name, System.Xml.XmlNode XmlBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveXml", new object[] {
                    name,
                    XmlBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSaveXml(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SaveXmlAsync(string name, System.Xml.XmlNode XmlBody) {
        this.SaveXmlAsync(name, XmlBody, null);
    }
    
    /// <remarks/>
    public void SaveXmlAsync(string name, System.Xml.XmlNode XmlBody, object userState) {
        if ((this.SaveXmlOperationCompleted == null)) {
            this.SaveXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveXmlOperationCompleted);
        }
        this.InvokeAsync("SaveXml", new object[] {
                    name,
                    XmlBody}, this.SaveXmlOperationCompleted, userState);
    }
    
    private void OnSaveXmlOperationCompleted(object arg) {
        if ((this.SaveXmlCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveXmlCompleted(this, new SaveXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MethodWithoutParameters", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public TestClassSimple MethodWithoutParameters() {
        object[] results = this.Invoke("MethodWithoutParameters", new object[0]);
        return ((TestClassSimple)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMethodWithoutParameters(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MethodWithoutParameters", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public TestClassSimple EndMethodWithoutParameters(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TestClassSimple)(results[0]));
    }
    
    /// <remarks/>
    public void MethodWithoutParametersAsync() {
        this.MethodWithoutParametersAsync(null);
    }
    
    /// <remarks/>
    public void MethodWithoutParametersAsync(object userState) {
        if ((this.MethodWithoutParametersOperationCompleted == null)) {
            this.MethodWithoutParametersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMethodWithoutParametersOperationCompleted);
        }
        this.InvokeAsync("MethodWithoutParameters", new object[0], this.MethodWithoutParametersOperationCompleted, userState);
    }
    
    private void OnMethodWithoutParametersOperationCompleted(object arg) {
        if ((this.MethodWithoutParametersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MethodWithoutParametersCompleted(this, new MethodWithoutParametersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class TestClassSimple {
    
    private int fIntField;
    
    private decimal fDecimalField;
    
    private System.DateTime fDateTimeField;
    
    private string fStringField;
    
    /// <remarks/>
    public int FInt {
        get {
            return this.fIntField;
        }
        set {
            this.fIntField = value;
        }
    }
    
    /// <remarks/>
    public decimal FDecimal {
        get {
            return this.fDecimalField;
        }
        set {
            this.fDecimalField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime FDateTime {
        get {
            return this.fDateTimeField;
        }
        set {
            this.fDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string FString {
        get {
            return this.fStringField;
        }
        set {
            this.fStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class TestClass {
    
    private int fIntField;
    
    private decimal fDecimalField;
    
    private System.DateTime fDateTimeField;
    
    private string fStringField;
    
    private TestClassSimple[] listTestClassSimpleField;
    
    /// <remarks/>
    public int FInt {
        get {
            return this.fIntField;
        }
        set {
            this.fIntField = value;
        }
    }
    
    /// <remarks/>
    public decimal FDecimal {
        get {
            return this.fDecimalField;
        }
        set {
            this.fDecimalField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime FDateTime {
        get {
            return this.fDateTimeField;
        }
        set {
            this.fDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string FString {
        get {
            return this.fStringField;
        }
        set {
            this.fStringField = value;
        }
    }
    
    /// <remarks/>
    public TestClassSimple[] ListTestClassSimple {
        get {
            return this.listTestClassSimpleField;
        }
        set {
            this.listTestClassSimpleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void HeloWordCompletedEventHandler(object sender, HeloWordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HeloWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HeloWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void DoSmthWithTestClassSimpleCompletedEventHandler(object sender, DoSmthWithTestClassSimpleCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DoSmthWithTestClassSimpleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DoSmthWithTestClassSimpleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public TestClassSimple Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((TestClassSimple)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void DoSmthWithTestClassCompletedEventHandler(object sender, DoSmthWithTestClassCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DoSmthWithTestClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DoSmthWithTestClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public TestClass Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((TestClass)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SaveXmlCompletedEventHandler(object sender, SaveXmlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void MethodWithoutParametersCompletedEventHandler(object sender, MethodWithoutParametersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MethodWithoutParametersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MethodWithoutParametersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public TestClassSimple Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((TestClassSimple)(this.results[0]));
        }
    }
}
