/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.nordstrom.event.rosettastone;
/** Channel is an identifier enum that represents the part of the Nordstrom family of businesses
    the app, website, or other source is affiliated with.
    If a new channel is added, the producer must version this schema.

  * UNKNOWN : Default value for when reader doesn't recognize the value
  * OMNI: Omni-market meaning all channels.  Should only be used if there is no differentiation at all between the code-paths and experience regardless of channel.
  * FULL_LINE: Full price selling stores, local and digital experiences
  * RACK: Nordstrom Rack physical and digital experiences
  * HAUTELOOK: HauteLook
  * TRUNKCLUB: Trunk Club physical and digital experiences
  * CASHSTAR : CashStar
  * EXTERNAL : Outside of Nordstrom channels */
@org.apache.avro.specific.AvroGenerated
public enum Channel implements org.apache.avro.generic.GenericEnumSymbol<Channel> {
  UNKNOWN, OMNI, FULL_LINE, RACK, HAUTELOOK, TRUNKCLUB, CASHSTAR, EXTERNAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Channel\",\"namespace\":\"com.nordstrom.event.rosettastone\",\"doc\":\"Channel is an identifier enum that represents the part of the Nordstrom family of businesses\\r\\n    the app, website, or other source is affiliated with.\\r\\n    If a new channel is added, the producer must version this schema.\\r\\n\\r\\n  * UNKNOWN : Default value for when reader doesn't recognize the value\\r\\n  * OMNI: Omni-market meaning all channels.  Should only be used if there is no differentiation at all between the code-paths and experience regardless of channel.\\r\\n  * FULL_LINE: Full price selling stores, local and digital experiences\\r\\n  * RACK: Nordstrom Rack physical and digital experiences\\r\\n  * HAUTELOOK: HauteLook\\r\\n  * TRUNKCLUB: Trunk Club physical and digital experiences\\r\\n  * CASHSTAR : CashStar\\r\\n  * EXTERNAL : Outside of Nordstrom channels\",\"symbols\":[\"UNKNOWN\",\"OMNI\",\"FULL_LINE\",\"RACK\",\"HAUTELOOK\",\"TRUNKCLUB\",\"CASHSTAR\",\"EXTERNAL\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
