/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.nordstrom.event.rosettastone;
/** Employee Id type identifier enum

  * UNKNOWN : Default value for when reader doesn't recognize the value
  * EMPLOYEE_NUMBER : Employee number
  * EMPLOYEE_EMAIL : Employee email address (Not employee's personal email) */
@org.apache.avro.specific.AvroGenerated
public enum EmployeeIdType implements org.apache.avro.generic.GenericEnumSymbol<EmployeeIdType> {
  UNKNOWN, EMPLOYEE_NUMBER, EMPLOYEE_EMAIL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EmployeeIdType\",\"namespace\":\"com.nordstrom.event.rosettastone\",\"doc\":\"Employee Id type identifier enum\\r\\n\\r\\n  * UNKNOWN : Default value for when reader doesn't recognize the value\\r\\n  * EMPLOYEE_NUMBER : Employee number\\r\\n  * EMPLOYEE_EMAIL : Employee email address (Not employee's personal email)\",\"symbols\":[\"UNKNOWN\",\"EMPLOYEE_NUMBER\",\"EMPLOYEE_EMAIL\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
