### https://medium.com/faun/hello-world-of-kubernetes-part-1-d1153fc2fc37
### https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

apiVersion: v1
kind: Pod
metadata:
  name: testserver
  namespace: default
  labels:
    app: testserver
spec:
  containers:
  - name: testserver
    image: testserver
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 1337
