### https://medium.com/faun/hello-world-of-kubernetes-part-1-d1153fc2fc37

apiVersion: v1
kind: Pod
metadata:
    labels:
        app: testserver
spec:
    containers:
    - name: testserver
      image: testserver
      ports:
      - containerPort: 1337
