/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.nordstrom.event.secure;
/** Nordstrom data classification sensitivity levels. See the
     [full definitions](https://gitlab.nordstrom.com/SecurityStandards/SecurityStandardsV1/blob/main/DataClassification.md). */
@org.apache.avro.specific.AvroGenerated
public enum DataClassification implements org.apache.avro.generic.GenericEnumSymbol<DataClassification> {
  RESTRICTED, SENSITIVE, CONFIDENTIAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DataClassification\",\"namespace\":\"com.nordstrom.event.secure\",\"doc\":\"Nordstrom data classification sensitivity levels. See the\\r\\n     [full definitions](https://gitlab.nordstrom.com/SecurityStandards/SecurityStandardsV1/blob/main/DataClassification.md).\",\"symbols\":[\"RESTRICTED\",\"SENSITIVE\",\"CONFIDENTIAL\"],\"default\":\"RESTRICTED\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
