version: '3.3'

services:
  web:
    image: dockersamples/k8s-wordsmith-web
    ports:
     - "8080:8080"

  words:
    image: dockersamples/k8s-wordsmith-api
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M

  db:
    image: dockersamples/k8s-wordsmith-db
