// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.example
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TestTypes : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""TestTypes"",""namespace"":""org.example"",""fields"":[{""name"":""fBoolean"",""type"":""boolean""},{""name"":""fInt"",""type"":[""int"",""null""]},{""name"":""fLong"",""type"":[""long"",""null""]},{""name"":""fFloat"",""type"":[""float"",""null""]},{""name"":""fDouble"",""type"":[""double"",""null""]},{""name"":""fString"",""type"":[""string"",""null""]},{""name"":""fEnum"",""type"":{""type"":""enum"",""name"":""TestEnum"",""namespace"":""org.example"",""symbols"":[""Unknown"",""First"",""Second"",""Third"",""Fourth"",""Fifth""]}}]}");
		private bool _fBoolean;
		private System.Nullable<System.Int32> _fInt;
		private System.Nullable<System.Int64> _fLong;
		private System.Nullable<System.Single> _fFloat;
		private System.Nullable<System.Double> _fDouble;
		private string _fString;
		private org.example.TestEnum _fEnum;
		public virtual Schema Schema
		{
			get
			{
				return TestTypes._SCHEMA;
			}
		}
		public bool fBoolean
		{
			get
			{
				return this._fBoolean;
			}
			set
			{
				this._fBoolean = value;
			}
		}
		public System.Nullable<System.Int32> fInt
		{
			get
			{
				return this._fInt;
			}
			set
			{
				this._fInt = value;
			}
		}
		public System.Nullable<System.Int64> fLong
		{
			get
			{
				return this._fLong;
			}
			set
			{
				this._fLong = value;
			}
		}
		public System.Nullable<System.Single> fFloat
		{
			get
			{
				return this._fFloat;
			}
			set
			{
				this._fFloat = value;
			}
		}
		public System.Nullable<System.Double> fDouble
		{
			get
			{
				return this._fDouble;
			}
			set
			{
				this._fDouble = value;
			}
		}
		public string fString
		{
			get
			{
				return this._fString;
			}
			set
			{
				this._fString = value;
			}
		}
		public org.example.TestEnum fEnum
		{
			get
			{
				return this._fEnum;
			}
			set
			{
				this._fEnum = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.fBoolean;
			case 1: return this.fInt;
			case 2: return this.fLong;
			case 3: return this.fFloat;
			case 4: return this.fDouble;
			case 5: return this.fString;
			case 6: return this.fEnum;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.fBoolean = (System.Boolean)fieldValue; break;
			case 1: this.fInt = (System.Nullable<System.Int32>)fieldValue; break;
			case 2: this.fLong = (System.Nullable<System.Int64>)fieldValue; break;
			case 3: this.fFloat = (System.Nullable<System.Single>)fieldValue; break;
			case 4: this.fDouble = (System.Nullable<System.Double>)fieldValue; break;
			case 5: this.fString = (System.String)fieldValue; break;
			case 6: this.fEnum = (org.example.TestEnum)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
