using DevExpress.XtraEditors;

namespace TestPivotGrid
{
    public partial class MainForm : XtraForm
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource.Fill();
            pivotGridControl.FieldsCustomization(splitContainerControl.Panel1);
        }
    }
}
