using DevExpress.XtraEditors;

namespace TestPivotGrid
{
    public partial class MainForm : XtraForm
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource.Fill();
            pivotGridControl.FieldsCustomization(splitContainerControl.Panel1);
        }

        private void BtnAllowDragClick(object sender, System.EventArgs e)
        {
            pivotGridControl.OptionsCustomization.AllowDrag = !pivotGridControl.OptionsCustomization.AllowDrag;
            pivotGridControl.OptionsCustomization.AllowDragInCustomizationForm = !pivotGridControl.OptionsCustomization.AllowDragInCustomizationForm;
        }
    }
}
