using System;
using DevExpress.XtraEditors;
using DevExpress.XtraPivotGrid;

namespace TestPivotGrid
{
    public partial class MainForm : XtraForm
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource.Fill();

            pivotGridControl.ShowingCustomizationForm += PivotGridControlShowingCustomizationForm;
            pivotGridControl.ShowCustomizationForm += PivotGridControlShowCustomizationForm;

            pivotGridControl.FieldsCustomization(splitContainerControl.Panel1);
        }

        private void PivotGridControlShowingCustomizationForm(object sender, CustomizationFormShowingEventArgs e)
        {
            
        }

        private void PivotGridControlShowCustomizationForm(object sender, EventArgs e)
        {
            
        }

        private void BtnAllowDragClick(object sender, EventArgs e)
        {
            pivotGridControl.OptionsCustomization.AllowDrag = !pivotGridControl.OptionsCustomization.AllowDrag;
            pivotGridControl.OptionsCustomization.AllowDragInCustomizationForm = !pivotGridControl.OptionsCustomization.AllowDragInCustomizationForm;
        }
    }
}
