//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2914.16
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.2914.16.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.Web.Services;


[System.Web.Services.WebServiceBindingAttribute(Name="net.xmethods.services.stockquote.StockQuoteBinding", Namespace="http://www.themindelectric.com/wsdl/net.xmethods.services.stockquote.StockQuote/")]
public class netxmethodsservicesstockquoteStockQuoteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public netxmethodsservicesstockquoteStockQuoteService() {
        this.Url = "http://64.39.29.211:9090/soap";
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:xmethods-delayed-quotes#getQuote", RequestNamespace="urn:xmethods-delayed-quotes", ResponseNamespace="urn:xmethods-delayed-quotes")]
    [return: System.Xml.Serialization.SoapElementAttribute("Result")]
    public System.Single getQuote(string symbol) {
        object[] results = this.Invoke("getQuote", new object[] {
                    symbol});
        return ((System.Single)(results[0]));
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public System.IAsyncResult BegingetQuote(string symbol, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getQuote", new object[] {
                    symbol}, callback, asyncState);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public System.Single EndgetQuote(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Single)(results[0]));
    }
}
