//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleAddress
    {
        public int Id { get; set; }
        public int PeopleId { get; set; }
        public int AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual People People { get; set; }
    }
}
