//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Victim
    {
        public int Id { get; set; }
        public Nullable<int> FInt { get; set; }
        public Nullable<bool> FBit { get; set; }
    }
}
